### ISSUE TITLE
go: inconsistent vendoring in /build/source/i2ywm

### ISSUE THREAD

**Issue by donovanglover** [xplshn/wayland-imd#1]
Hello! Found your project from your post and wanted to try it out. Seems like there's a dependency issue somewhere since I get the following when trying to build with Nix:

```go
go: inconsistent vendoring in /build/source/i2ywm:
        github.com/dlasky/gotk3-layershell@v0.0.0-20240515133811-5c5115f0d774: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/fsnotify/fsnotify@v1.7.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/gotk3/gotk3@v0.6.5-0.20240618185848-ff349ae13f56: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.org/x/sys@v0.24.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

        To ignore the vendor directory, use -mod=readonly or -mod=mod.
        To sync the vendor directory, run:
                go mod vendor
```

**Comment by donovanglover** [comment]
Closing since this was a skill issue on my part (needed to use `sourceRoot`).

**Comment by xplshn** [comment]
This is also not well-written, and its very incomplete compared to the original.

https://github.com/Geronymos/desktop-icons

**Comment by donovanglover** [comment]
`desktop-icons` is pretty cool indeed. Would be interesting to see a modern language used with the addition of more features like sorting etc.

**Comment by xplshn** [comment]
> `desktop-icons` is pretty cool indeed. Would be interesting to see a modern language used with the addition of more features like sorting etc.

C is very much modern if you want that (personally, I don't, I like C99 because it is clear and readable), I wanted to rewrite it in Go however because it is easier for others to understand what the code is doing, and to collaborate. + Go is easy to statically link.

Anyways, thanks for trying this out, even if I currently have no time to work on it, it was just a thing I made in an hour and a half
